rules:
    - name: ENC[AES256_GCM,data:wlwwlJUL,iv:74VgvPvbyucpGyuSaAHq1j4v6FCs/HoxzbEOCM1H8BU=,tag:b5YnKuhwG4t6jLFYmJhu+g==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:Z+rjdX8BhpaCIg==,iv:I/knEjbkhvId2u9knzaglvH94WAQmSq6XM5mMxKysyk=,tag:mx4JOcx8hMCySy/Q5N/HUg==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:2X9BY8WYgrI7MBg0f8JCcohI5CoPKTSKYwolB9oD81XlQJTURyL8S1q61np1U1A1DL8LsfGHcUJgZldgKw==,iv:9AfvFPepdwd1yTAYphiwMUc7Cn6gIVYzgqPL0LCmjMs=,tag:BhAMtL5EmJYTOm/OgD6ORg==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:L3t/PxpXIrorXW3XRwVy/+97mUeNpzOcAWvs,iv:1SRelsgCHvspmqvUIAf3DKOgAdMQ8yP/sNHDu0oXSSk=,tag:V7jOsWzYdbxlo9l16bg+yQ==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:KjGjQJSpNZYP1n5j1QX8Mg==,iv:rbDuBjkD2zIYC1LzVhPZhjB4m0lwc5gbNsVJ35SsWcU=,tag:/AqP0ogARMQBo5fSjp14zQ==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:fEgRAaNG1w==,iv:laT06mIyi1ZyVrZAyg401TRKMatha8cZ3EqKbEUMXYs=,tag:x4I7vNEruHzm8y/L9r3psQ==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:uaHdAeBCspzWqZjSvhwxzJ3b4Z90YvfUvqO0Al+inLt4J1+DHgRUEZE5QpzYH1Jcf2qOq49cjz3C1tKCCidyLFhFSPFjyRBtGShJ37J1oBtMWf4OiJV/YdM1TprRnMheLdciUt3Hr7U0dbTfwfAJYyxH,iv:vrtmMnafeLyYHvVgPaNJJ2Kcmp1xKMtPZfl96Y7/Mvk=,tag:yaqYMJO5KMadDm/3V5NUpQ==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:+xsNugKrSMmS0SI/h6PKeS5mVz6buzDyOmnl9hIQ4wfsoWzJe87saQ+ES2eADOt7aXrOxqQ4s41SsgfI117XIL7+7RveYdhhqrULUjAw0azyrDJFS3GnxPdXgCc+iFbSai+hdP/IkQs=,iv:dCB6Uyc/NWX1s0Tw8YYHUpqsFSQJBltPQJrEEKpk8jc=,tag:Cdt9KC9MHNWTpdW8trRNkw==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:cNTxXkHAJlYUqbN4gjen,iv:b0i8ISbXLjRUt2EnBXDoUKf48+BZn1t168ZEoGjp2U8=,tag:D6nfl//vXbrOVn5+uXbmHg==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:fEgRAaNG1w==,iv:laT06mIyi1ZyVrZAyg401TRKMatha8cZ3EqKbEUMXYs=,tag:x4I7vNEruHzm8y/L9r3psQ==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:FzDu6wvIXNFkMEpPS3slLNWAcYjV5J+qzW9WbNZa7mc7VM3uCS/bRfm/egK/vKm5MY1VnsWpZPf4CIp2CCz5ppqNGlUn7Wdgv6+WxZTmtSd+8omloI6D2vNbBHxbUylo,iv:UU3FbtBg6xJD+6t/JUBNm/TebegMYeXU4aHOQyY5Pu8=,tag:1qBwHCFYEl39P6W2opq+Nw==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:yAJGU2V/waGkKnM7vrGx3pPn2ybXdBCU5p8C6JUO8p2U6VgNRa4UYr3fESvi6//1xOweh8ucjDqlkGSuWY+DWZJnik2Wjaua12OYKcVskg7o3bZFvioHSBOqaQH0Wabm3NrWMi3kIa4=,iv:3Rh9T7mkQjt9uhesgLmexDjn1SGbDDRK79KnDN4C2HI=,tag:zDcOtcGe/aT0NJwTdAu4KQ==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:X1pjFHQJjxRxGRZK/y8NrgwWZOFYSG4Ro58+/zviYw==,iv:vzmb+/Izokd1GaH6Xppj60P3EmpZ6v1aR494XwQ+RzI=,tag:J7PccKYbR23dr0+2i5Zjkg==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - regex: ENC[AES256_GCM,data:1y4dJM9kuOIiNAnkcmWPIkttZNdXH8TFkek1bKWcdhTfd88v6e66zmXUOg1etbA/mbMpbIc9knMyc9Ap8eHI,iv:ONTZd4C0ZgFsWqH8LehAPrinHut/L7WPOlnDzRzTaDY=,tag:yK7Gt/4LpPbKkHmu+lvPEQ==,type:str]
        - python: ENC[AES256_GCM,data:KHNSocNI7tT5WsNis9nM4ZxGXQCSO98WF7xrZJuEt9KJOSpq/InJ78iC7ZGVeYOKjEMOIf9D2bBl1w1KWhcDLJJmIGGZzXjN2tphXTbSLKthswBF7sm3uuv+uwcZoR437nNOx4SwTjjvB56XfBSxx7q+4Fvg++xxvpy435ZR+JqiZ+BF9MQqQEqlnNacMSlFqC6izK3kwc+bBzHYqaqVimlZyevoVJkYZ4y2d8TisN46G0UYh/0WcoahewDMAlVWWD2zzv1BkmizwbEqSRQ5HZBVV9u8rrdGBZ7I/9IQS9DsXjFjc1/DJPVPIPmlfQkx2/Pxo4HUESW13q+R+IeL5X+dLWv8J6AZCbEC+SWtYC2ShIg78Xaf5Aiz4jd5nBeCTqMQh6loudWJnrYepl9cNxqgbYhxhBd2DFNGEz9tDwkrTQ==,iv:rJZ+Pa5VPKGvgj31mLyY1VJg6M9CMIGcye5CL4A6N+8=,tag:UecIiYTc2r8CkZIUhzgScw==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:lKKBSL8hukFLFFqclwJlAp7n6DVI9+hozkWAl81Mcc8pQvAYsV4BOgTRvq0kfwKNKEqA2TzMflE0pxwGpF1QccJXUnpwOJqZfwucxPSpJYV91w==,iv:wNAgcP0mNVq9T4bPgsitZqDleJsEmwX7qMXLGdnnnj8=,tag:CsTaC1HnLj7T/A7CJZO+JA==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:3y23v/b7Uc0w1WPIbLig53Q=,iv:CGJ4DGlzLBTD4NnE+vqiW5vBp0dmfXQ4ZX44z1wF698=,tag:AIyTuX4ClwoNjibD9TgJPA==,type:str]
      locations: ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:EqYXXPijZKbviD/+bhuuUrVzz0CbH4IM,iv:CZq8ZPZLqyfiZ6Si6rOXvb5GxHQHtwHu/E2UCDcDkNk=,tag:6sG7esICnQBemdbS3NK03A==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:vYwzYrLhn+60M+hFtOG6HY1CRhS8f6Aax2wjErOlPM8ii4C4xyOoeKZlXbZBgfG9N7sAhTOe7DDZca5AVcvu9MvVFY8nKKPZe3E=,iv:F+E4v7cBrAdlBo/GOg4M5dht+D3KHyq+lfAPH6oGgtA=,tag:0zExdVNjj73XgxSHNL2eyQ==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:vVvSGSZ2ieZkxhqQ7ORVWv0u/LxjQ65yxboWWTNuOk1uBpifmdwyMEuBFCAS4meNFFSJOY/L8sXWG80t6DHmuh3yZvY82ahgL7JM7Px+CPZz2GzNGLsvpoyxNwJ+62rWcUgi6D1gnj0L26j7k/8VDPSJdhn6,iv:qtXdjSMMOYMDcrLkvuYXvAGfb4eM+4lEDRAfyUTESqo=,tag:y5/vZF0hE+r3Vb1yh7vj6g==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:YC+2/ppz85EuK4d7OEH7kH5/BKEu2QCz,iv:0eyQ6GK8S9Zk70vJRzZ/ijH7bidFI55Dl1t2msygW4M=,tag:22Ng+72TITNjGwQmBLCB0g==,type:str]
      locations:
        - ENC[AES256_GCM,data:pPSTrosXRUV+,iv:fw89SdD6WGY7RckoLbOns7mUD1s3XNJZ27SGUoUK2po=,tag:KZiFQLsPJv5sHfw64xI/FQ==,type:str]
        - ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            startswith: ENC[AES256_GCM,data:RCC4oYNTJA+wY902QM1F,iv:rbMDu6FTmitJajjSLZ9py+rMNObdsIVHbfrr9BsRz9c=,tag:5OXbUlYfaf+VeAVSoGBzDQ==,type:str]
      actions:
        - move: ENC[AES256_GCM,data:YUMFVOxQeGn8i0N4kUZTYz9aqT0j/LKB6Sg=,iv:Bcff880z5iDMvd3vI1Z5tDBAvrarNOQ0kTAhvwZxZrg=,tag:PpwrY2rQCqvY3YaNXHmAhQ==,type:str]
sops:
    age:
        - recipient: age1y7g3ehjwu055n3h0vz0yvudnh4p0tu849m2q64juxt9qxvpvt39q6z63la
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN1NIL2g5RVRiWUw5M3p6
            eUxlN0pWOVVUby92ZW9HVUpDeVlqajJCbEY4CmNFVHJnU3JkWFg5aCs1OE14NjN2
            NWZoeFd6L0M3VnlPNTNRSXVmU0N2bk0KLS0tIExlbDNpVFBaVWVnc2xpNjZIYTN2
            SUdjbjRPbmZSMFZCWVBZNVZpNFZKd2sKdntmxla9crG8ir+3GonHfYHp42Lbzikh
            Xljz8ruXlxeayKqF0/8CQDc0brNQ8mI+p6xrCjfGo1xmiOmMPHYkFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-02T16:07:47Z"
    mac: ENC[AES256_GCM,data:X137FFF7CfTwzW103GRzGr77j3oIha+XokSkod7c+GBEID0Zy67sfsv0PnhHtvYg5VobJIPBhJVXPQHIG0zbTKITBpcaYhSfKPGYa+XvcFCXhQ9Tq4wv7G9mSLfRuXHSda6eqS++MZqt2LdbNYVhqj5VKFQL3y6psj7DpQQsBA8=,iv:gSYefuJVdp8J1U1KpuQxaYtYKlV8sOV/QH7hAA+4D7o=,tag:XfOq2MzN9Qzqb8GBdXtWmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
