rules:
    - name: ENC[AES256_GCM,data:wlwwlJUL,iv:74VgvPvbyucpGyuSaAHq1j4v6FCs/HoxzbEOCM1H8BU=,tag:b5YnKuhwG4t6jLFYmJhu+g==,type:str]
      locations: ENC[AES256_GCM,data:ffGH1uJGnRGaQ9Q=,iv:T/DH8EDn+XSLrK4EART/8L/RIpCRw0fV59TWF5vZCd0=,tag:1yGf6izqfvgXG1MCmYw0EA==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:Benf,iv:IVpj8Dgb+jcbuC19PAUzf1vM313na3A1bm0YQVfZ9jE=,tag:9rp0+Q3r7hi2s+XfVwCI2w==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:Z+rjdX8BhpaCIg==,iv:I/knEjbkhvId2u9knzaglvH94WAQmSq6XM5mMxKysyk=,tag:mx4JOcx8hMCySy/Q5N/HUg==,type:str]
            case_sensitive: ENC[AES256_GCM,data:6Cq4i/o=,iv:bpyHypbgUqrnj/a80+ifqi5f+TrXTw4ShkgYhOh21Lk=,tag:UNXPS+A04vSMhFE8CQCmXA==,type:bool]
        - filecontent: ENC[AES256_GCM,data:2X9BY8WYgrI7MBg0f8JCcohI5CoPKTSKYwolB9oD81XlQJTURyL8S1q61np1U1A1DL8LsfGHcUJgZldgKw==,iv:9AfvFPepdwd1yTAYphiwMUc7Cn6gIVYzgqPL0LCmjMs=,tag:BhAMtL5EmJYTOm/OgD6ORg==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:L3t/PxpXIrorXW3XRwVy/+97mUeNpzOcAWvs,iv:1SRelsgCHvspmqvUIAf3DKOgAdMQ8yP/sNHDu0oXSSk=,tag:V7jOsWzYdbxlo9l16bg+yQ==,type:str]
            on_conflict: ENC[AES256_GCM,data:swHkMQ==,iv:cPGcV4ubgHUnYueSF9kpB+C8qckSBzaQN7WDZbEfTSY=,tag:Fy55ZsRdRB7N3Y21PtHsdQ==,type:str]
    - name: ENC[AES256_GCM,data:KjGjQJSpNZYP1n5j1QX8Mg==,iv:rbDuBjkD2zIYC1LzVhPZhjB4m0lwc5gbNsVJ35SsWcU=,tag:/AqP0ogARMQBo5fSjp14zQ==,type:str]
      locations: ENC[AES256_GCM,data:WzsfapN2mqk1SZA=,iv:/NRYQNpViN2ovT2WBYhNOtwMRnKr6F9Wf6ZfL8HGEJY=,tag:siCIGAv7/vlOgs+BazLUoQ==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:Tsye,iv:B3S2vwTI9l61s65ltY9RjlLbphCwCKRHqjISDB52r2I=,tag:+7aWf9kAzeU/jhlckfkI1w==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:FNTotbcgVg==,iv:3lJc0s5QsPx/JgcItESeayAmbcWRYQMmmBitxBbQzYI=,tag:bPtFAt+ZfmOZ5ddep0B5pg==,type:str]
            case_sensitive: ENC[AES256_GCM,data:BwAeU7o=,iv:tDJC3exbgB2iFiCgBbSOX4cNGhPU390aEHFKJ3AgFgo=,tag:vcs1wfHRNOaoLg+OAs0P0g==,type:bool]
        - filecontent: ENC[AES256_GCM,data:uaHdAeBCspzWqZjSvhwxzJ3b4Z90YvfUvqO0Al+inLt4J1+DHgRUEZE5QpzYH1Jcf2qOq49cjz3C1tKCCidyLFhFSPFjyRBtGShJ37J1oBtMWf4OiJV/YdM1TprRnMheLdciUt3Hr7U0dbTfwfAJYyxH,iv:vrtmMnafeLyYHvVgPaNJJ2Kcmp1xKMtPZfl96Y7/Mvk=,tag:yaqYMJO5KMadDm/3V5NUpQ==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:+xsNugKrSMmS0SI/h6PKeS5mVz6buzDyOmnl9hIQ4wfsoWzJe87saQ+ES2eADOt7aXrOxqQ4s41SsgfI117XIL7+7RveYdhhqrULUjAw0azyrDJFS3GnxPdXgCc+iFbSai+hdP/IkQs=,iv:dCB6Uyc/NWX1s0Tw8YYHUpqsFSQJBltPQJrEEKpk8jc=,tag:Cdt9KC9MHNWTpdW8trRNkw==,type:str]
            on_conflict: ENC[AES256_GCM,data:cwRBvg==,iv:+Rmp+EjNNRMSAXt06j27DejVW/eUyk941mFbC9egb8M=,tag:zR/AiMSCusR/1xxWNfN8mg==,type:str]
    - name: ENC[AES256_GCM,data:cNTxXkHAJlYUqbN4gjen,iv:b0i8ISbXLjRUt2EnBXDoUKf48+BZn1t168ZEoGjp2U8=,tag:D6nfl//vXbrOVn5+uXbmHg==,type:str]
      locations: ENC[AES256_GCM,data:BXfkVwy4FSVhoww=,iv:igCntbK9l72nOxfVtgOZGMjg7nx/EI2SYIO8x3fTd+o=,tag:Nq1WaK1XSs6z0yGcd13hLA==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:OwOO,iv:jyAiiWEylMqepXVO2VyHq+APv0PS4jWW5BqKu31Mfq8=,tag:V+onyj+XIVxr7I5gy6kA7w==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:fEgRAaNG1w==,iv:laT06mIyi1ZyVrZAyg401TRKMatha8cZ3EqKbEUMXYs=,tag:x4I7vNEruHzm8y/L9r3psQ==,type:str]
            case_sensitive: ENC[AES256_GCM,data:FNlEPvo=,iv:dlbAIkxeWqU1Se3EDaUzx8FbZd6jRZ0VB9o6enI+cz0=,tag:fQqVEDAOnxrgJ92bcQ5Ayw==,type:bool]
        - filecontent: ENC[AES256_GCM,data:FzDu6wvIXNFkMEpPS3slLNWAcYjV5J+qzW9WbNZa7mc7VM3uCS/bRfm/egK/vKm5MY1VnsWpZPf4CIp2CCz5ppqNGlUn7Wdgv6+WxZTmtSd+8omloI6D2vNbBHxbUylo,iv:UU3FbtBg6xJD+6t/JUBNm/TebegMYeXU4aHOQyY5Pu8=,tag:1qBwHCFYEl39P6W2opq+Nw==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:yAJGU2V/waGkKnM7vrGx3pPn2ybXdBCU5p8C6JUO8p2U6VgNRa4UYr3fESvi6//1xOweh8ucjDqlkGSuWY+DWZJnik2Wjaua12OYKcVskg7o3bZFvioHSBOqaQH0Wabm3NrWMi3kIa4=,iv:3Rh9T7mkQjt9uhesgLmexDjn1SGbDDRK79KnDN4C2HI=,tag:zDcOtcGe/aT0NJwTdAu4KQ==,type:str]
            on_conflict: ENC[AES256_GCM,data:D8eK2w==,iv:XrOhv84nwT/VFJYUIkxDta90jXB2VPfRR3mf2TY/XYk=,tag:qm8dnwi/PEqI6y4EiaFTqw==,type:str]
    - name: ENC[AES256_GCM,data:X1pjFHQJjxRxGRZK/y8NrgwWZOFYSG4Ro58+/zviYw==,iv:vzmb+/Izokd1GaH6Xppj60P3EmpZ6v1aR494XwQ+RzI=,tag:J7PccKYbR23dr0+2i5Zjkg==,type:str]
      locations: ENC[AES256_GCM,data:ECB8AyrfsuioHOI=,iv:MZd5E9cuQPU+2h/N+R6APliu9UC4GJS34IcMSpJNw9w=,tag:TZFXqqCwXY20hxo1RSLcGQ==,type:str]
      filters:
        - regex: ENC[AES256_GCM,data:1y4dJM9kuOIiNAnkcmWPIkttZNdXH8TFkek1bKWcdhTfd88v6e66zmXUOg1etbA/mbMpbIc9knMyc9Ap8eHI,iv:ONTZd4C0ZgFsWqH8LehAPrinHut/L7WPOlnDzRzTaDY=,tag:yK7Gt/4LpPbKkHmu+lvPEQ==,type:str]
        - python: ENC[AES256_GCM,data:KHNSocNI7tT5WsNis9nM4ZxGXQCSO98WF7xrZJuEt9KJOSpq/InJ78iC7ZGVeYOKjEMOIf9D2bBl1w1KWhcDLJJmIGGZzXjN2tphXTbSLKthswBF7sm3uuv+uwcZoR437nNOx4SwTjjvB56XfBSxx7q+4Fvg++xxvpy435ZR+JqiZ+BF9MQqQEqlnNacMSlFqC6izK3kwc+bBzHYqaqVimlZyevoVJkYZ4y2d8TisN46G0UYh/0WcoahewDMAlVWWD2zzv1BkmizwbEqSRQ5HZBVV9u8rrdGBZ7I/9IQS9DsXjFjc1/DJPVPIPmlfQkx2/Pxo4HUESW13q+R+IeL5X+dLWv8J6AZCbEC+SWtYC2ShIg78Xaf5Aiz4jd5nBeCTqMQh6loudWJnrYepl9cNxqgbYhxhBd2DFNGEz9tDwkrTQ==,iv:rJZ+Pa5VPKGvgj31mLyY1VJg6M9CMIGcye5CL4A6N+8=,tag:UecIiYTc2r8CkZIUhzgScw==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:lKKBSL8hukFLFFqclwJlAp7n6DVI9+hozkWAl81Mcc8pQvAYsV4BOgTRvq0kfwKNKEqA2TzMflE0pxwGpF1QccJXUnpwOJqZfwucxPSpJYV91w==,iv:wNAgcP0mNVq9T4bPgsitZqDleJsEmwX7qMXLGdnnnj8=,tag:CsTaC1HnLj7T/A7CJZO+JA==,type:str]
            on_conflict: ENC[AES256_GCM,data:rpg9PA==,iv:QfFP6IpioI3swc3pGMkdcUSwU5UGY7+XbBsGZWfj65g=,tag:SANnLgeyFv4r5L+Jy0R5Pw==,type:str]
    - name: ENC[AES256_GCM,data:3y23v/b7Uc0w1WPIbLig53Q=,iv:CGJ4DGlzLBTD4NnE+vqiW5vBp0dmfXQ4ZX44z1wF698=,tag:AIyTuX4ClwoNjibD9TgJPA==,type:str]
      locations: ENC[AES256_GCM,data:w3/QzLbsc0j+xxE=,iv:DnrYM/8QHpDDmzEoB/nN6qjVDfWQStBYq7OXD7X9Hho=,tag:6UeRF7ZlCUmuEi8YwpOR/Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:Fw9w,iv:I/E+1GaRPEeccELtD4HpfcvRfTSI3njBDycIVHJr2PI=,tag:UtzzAR6FYBwaO77VENd7uQ==,type:str]
        - name:
            contains: ENC[AES256_GCM,data:EqYXXPijZKbviD/+bhuuUrVzz0CbH4IM,iv:CZq8ZPZLqyfiZ6Si6rOXvb5GxHQHtwHu/E2UCDcDkNk=,tag:6sG7esICnQBemdbS3NK03A==,type:str]
            case_sensitive: ENC[AES256_GCM,data:O9q6dI0=,iv:/2sb9w/sM6sfnn9w++7ORhbkt7hf0CtpsFLaewlmJIY=,tag:DCnOxM+l5DvRg3EIvqrk8A==,type:bool]
        - filecontent: ENC[AES256_GCM,data:vYwzYrLhn+60M+hFtOG6HY1CRhS8f6Aax2wjErOlPM8ii4C4xyOoeKZlXbZBgfG9N7sAhTOe7DDZca5AVcvu9MvVFY8nKKPZe3E=,iv:F+E4v7cBrAdlBo/GOg4M5dht+D3KHyq+lfAPH6oGgtA=,tag:0zExdVNjj73XgxSHNL2eyQ==,type:str]
      actions:
        - move:
            dest: ENC[AES256_GCM,data:KnVaoZtCKQUc/MaFZYTK7qA/aghLOcKsVU5nZdXD9ZHl58ptcOogrALxxwYvg/qsvnlB+Kgyq5kczyJ8z5aki18nmPTpmrlbi3lHA4s4ed9OEssY+baAPDLBlrooAXB4RG6nfJg0v6C7+g==,iv:lER4KpoJu47oliZ5xspzmIt67FIXWODbBafHZCytPBU=,tag:6N6I3qmyukVtlf8n3pOjPQ==,type:str]
            on_conflict: ENC[AES256_GCM,data:FSEJ3Q==,iv:/yYnno4l/r/oWoNSbfaIf3f9+Dek4bLJrKvJ4IRU5LE=,tag:Xg0HTV+qjk/m8mF9mNQb4w==,type:str]
    - name: ENC[AES256_GCM,data:YC+2/ppz85EuK4d7OEH7kH5/BKEu2QCz,iv:0eyQ6GK8S9Zk70vJRzZ/ijH7bidFI55Dl1t2msygW4M=,tag:22Ng+72TITNjGwQmBLCB0g==,type:str]
      locations:
        - ENC[AES256_GCM,data:pPSTrosXRUV+,iv:fw89SdD6WGY7RckoLbOns7mUD1s3XNJZ27SGUoUK2po=,tag:KZiFQLsPJv5sHfw64xI/FQ==,type:str]
        - ENC[AES256_GCM,data:1tZY6mQHmbqMZ6k=,iv:ZFyCfipD9DpbIoaHevb8v2QWqpppa+JNiS0ikVWcHLY=,tag:E0Eqnvpq4p99Jocu1jH49Q==,type:str]
      filters:
        - extension: ENC[AES256_GCM,data:7ORu,iv:dHhdfH1zIMkEFI7j3cGFdLjENnyqQXPGYeEiuZPVjPI=,tag:WcNPwiOjtlFvbQ6cV3EHvQ==,type:str]
        - name:
            startswith: ENC[AES256_GCM,data:RCC4oYNTJA+wY902QM1F,iv:rbMDu6FTmitJajjSLZ9py+rMNObdsIVHbfrr9BsRz9c=,tag:5OXbUlYfaf+VeAVSoGBzDQ==,type:str]
      actions:
        - move: ENC[AES256_GCM,data:YUMFVOxQeGn8i0N4kUZTYz9aqT0j/LKB6Sg=,iv:Bcff880z5iDMvd3vI1Z5tDBAvrarNOQ0kTAhvwZxZrg=,tag:PpwrY2rQCqvY3YaNXHmAhQ==,type:str]
sops:
    age:
        - recipient: age1y7g3ehjwu055n3h0vz0yvudnh4p0tu849m2q64juxt9qxvpvt39q6z63la
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN1NIL2g5RVRiWUw5M3p6
            eUxlN0pWOVVUby92ZW9HVUpDeVlqajJCbEY4CmNFVHJnU3JkWFg5aCs1OE14NjN2
            NWZoeFd6L0M3VnlPNTNRSXVmU0N2bk0KLS0tIExlbDNpVFBaVWVnc2xpNjZIYTN2
            SUdjbjRPbmZSMFZCWVBZNVZpNFZKd2sKdntmxla9crG8ir+3GonHfYHp42Lbzikh
            Xljz8ruXlxeayKqF0/8CQDc0brNQ8mI+p6xrCjfGo1xmiOmMPHYkFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-26T19:46:44Z"
    mac: ENC[AES256_GCM,data:kt//I/2M0iSjZ6Ke42amqEl3v+PLNLCKlxEBSbyHLiFFxOcLjdaWV5nw/H3+xVMxt44njDO/qRJVrfw45I7thN9nk5sEeCAfAqQH0gYYYGG4oAshdyG+JrIADpuyhr/BhS3ywLNpPO9oc/zyARZ3yQrgNjLCQk3s0hJrGMWFDJc=,iv:faUlUzDSqeylFmgBBxVZRDbFeW6UA9y+zSh/Tm4Tpgk=,tag:pt4GY6haC8gjkJb1sKfpcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
