" --- Settings ---

" Disable the VI compatibility mode
" This should be set first as it may affect other options!
set nocompatible

" Enable file types (detection, plugins and indentation)
filetype plugin indent on

" Enable syntax highlighting
syntax enable

" Set the color scheme
colorscheme catppuccin_macchiato
" Use 24-bit colors (required for the Catppuccin color schemes)
set termguicolors

" Highlight the current line
set cursorline
" Show line numbers
set number
" Use line numbers relative to the current line
set relativenumber
" Set the minimum number of lines above and below the cursor
set scrolloff=10
" Set the minimum number of columns to the sides of the cursor
set sidescrolloff=10;

" Use indentation from the current line when starting a new line
set autoindent
" Indent wrapped lines to match line start
set breakindent
" Use soft tabs (spaces) instead of hard tabs (\t) for indentation
set expandtab
" Align to the closest indentation level when shifting indentation
set shiftround
" Use the 'tabstop' value when shifting indentation with << and >>
set shiftwidth=0
" Auto-indent based on syntax (ignored if indenting via Treesitter)
set smartindent
" Use the `shiftwidth` value (=`tabstop`) when editing with Tab or BS
set softtabstop=-1
" Set the tab width for both soft and hard tabs
set tabstop=2

" Highlight all of the search results
set hlsearch
" Use case-insensitive search by default (unless `\C` is used)
set ignorecase
" Use incremental search (search as you type)
set incsearch
" Use case-sensitive search if any of the characters are uppercase
set smartcase

" Disable the default ruler (use the status line instead)
set noruler;
" Always show the status line
set laststatus=2
" Show the current command (e.g. f, t) on the command line
set showcmd
" Don't show mode on the command line (use the status line instead)
set noshowmode
" Ignore some patterns when expanding wildcards and completing names
set wildignore=*.docx,*.exe,*.flv,*.gif,*.img,*.jpg,*.pdf,*.png,*.pyc,*.xlsx
" Enable a completion menu on the command line
set wildmenu
" Set the command line completion mode
set wildmode=longest:full,full

" Make sure the airline_symbols variable is defined
if !exists("g:airline_symbols")
    let g:airline_symbols = {}
endif
" Use the powerline symbols (requires nerd font)
let g:airline_powerline_fonts = 1
" Disable the default maxlinenr symbol which causes problems
let g:airline_symbols.maxlinenr = ""
" Set the line number symbol (requires nerd font)
let g:airline_symbols.linenr = " \uE0A1"
" Set the column number symbol (requires nerd font)
let g:airline_symbols.colnr = " \uE0A3"
" Enable the built-in tabline extension
let g:airline#extensions#tabline#enabled = 1
" Show the unique tail for each path in tabline
let g:airline#extensions#tabline#formatter = "unique_tail_improved"
" Use the flame symbol from Powerline Extra Symbols (requires nerd font)
let g:airline#extensions#tabline#left_sep = "\uE0C0"
" Show buffer numbers in tabline
let g:airline#extensions#tabline#buffer_nr_show = 1
" Disable the built-in whitespace extension
let g:airline#extensions#whitespace#enabled = 0

" Allow for switching a buffer without saving (hide an abandoned buffer)
set hidden
" New horizontal splits are created below the current window
set splitbelow
" New vertical splits are created to the right of the current window
set splitright
" Set how long (in ms) to wait for a mapped sequence (default is 1000)
set timeoutlen=300
" Disable the bell sound (set the visual bell to do nothing)
set visualbell t_vb=

" --- Mappings ---

" Set the leader key
let mapleader=" "

" Quit the insert mode
inoremap jj <esc>
inoremap jk <esc>
inoremap kj <esc>

" Use Ctrl + w/h/j/k/l for switching windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <C-;> <C-w><C-w>

" Keep the visual selection when changing the indentation
vnoremap < <gv
vnoremap > >gv

" Use U for REDO
nnoremap U <C-r>

" Move faster with J/K
nnoremap J 5j
nnoremap K 5k

" Re-map the join command
nnoremap \ J
vnoremap \ J

" Remove the search highlight
nnoremap <Leader>/ :nohlsearch<CR>

